# Seeking
force-seekable=yes

# RAM
cache=yes
cache-secs=300
demuxer-max-back-bytes=256M
demuxer-max-bytes=256M
demuxer-readahead-secs=20

# Video
slang=en,eng
vo=gpu-next
profile=high-quality
video-sync=display-resample
interpolation=yes
gpu-context=waylandvk
gpu-api=vulkan

# Hardware Decoder Settings
hwdec=vaapi
hwdec-codecs=all
gpu-hwdec-interop=vaapi
vd-lavc-dr=yes

# HDR
hdr-compute-peak=yes
target-peak=auto
tone-mapping=bt.2390

# Audio
volume-max=150
volume=80

# Screenshots
screenshot-format=png
screenshot-png-compression=0
screenshot-high-bit-depth=yes
screenshot-png-filter=0
screenshot-sw=yes
screenshot-tag-colorspace=yes
screenshot-template="%f-%n"
screenshot-directory=~/Pictures/Screenshots/mpv

# General
keep-open=yes
hls-bitrate=max
prefetch-playlist=yes
loop-playlist=inf
